RAID = [
    "MADARCHOD TERI MAA KI CHUT ME GHUTKA KHAAKE THOOK DUNGA 🤣🤣",
    "TERE BEHEN K CHUT ME CHAKU DAAL KAR CHUT KA KHOON KAR DUGA",
    "TERI VAHEEN NHI HAI KYA? 9 MAHINE RUK SAGI VAHEEN DETA HU 🤣🤣🤩",
    "TERI MAA K BHOSDE ME AEROPLANEPARK KARKE UDAAN BHAR DUGA ✈️🛫",
    "TERI MAA KI CHUT ME SUTLI BOMB FOD DUNGA TERI MAA KI JHAATE JAL KE KHAAK HO JAYEGI💣",
    "TERI MAAKI CHUT ME SCOOTER DAAL DUGA👅",
    "TERE BEHEN K CHUT ME CHAKU DAAL KAR CHUT KA KHOON KAR DUGA",
    "TERE BEHEN K CHUT ME CHAKU DAAL KAR CHUT KA KHOON KAR DUGA",
    "TERI MAA KI CHUT KAKTE 🤱 GALI KE KUTTO 🦮 ME BAAT DUNGA PHIR 🍞 BREAD KI TARH KHAYENGE WO TERI MAA KI CHUT",
    "DUDH HILAAUNGA TERI VAHEEN KE UPR NICHE 🆙🆒😙",
    "TERI MAA KI CHUT ME ✋ HATTH DALKE 👶 BACCHE NIKAL DUNGA 😍",
    "TERI BEHN KI CHUT ME KELE KE CHILKE 🍌🍌😍",
    "TERI BHEN KI CHUT ME USERBOT LAGAAUNGA SASTE SPAM KE CHODE",
    "TERI VAHEEN DHANDHE VAALI 😋😛",
    "TERI MAA KE BHOSDE ME AC LAGA DUNGA SAARI GARMI NIKAL JAAYEGI",
    "TERI VAHEEN KO HORLICKS PEELAUNGA MADARCHOD😚",
    "TERI MAA KI GAAND ME SARIYA DAAL DUNGA MADARCHOD USI SARIYE PR TANG KE BACHE PAIDA HONGE 😱😱",
    "TERI MAA KO KOLKATA VAALE JITU BHAIYA KA LUND MUBARAK 🤩🤩",
    "TERI MUMMY KI FANTASY HU LAWDE, TU APNI BHEN KO SMBHAAL 😈😈",
    "TERA PEHLA BAAP HU MADARCHOD ",
    "TERI VAHEEN KE BHOSDE ME XVIDEOS.COM CHALA KE MUTH MAARUNGA 🤡😹",
    "TERI MAA KA GROUP VAALON SAATH MILKE GANG BANG KRUNGA🙌🏻☠️ ",
    "TERI ITEM KI GAAND ME LUND DAALKE,TERE JAISA EK OR NIKAAL DUNGA MADARCHOD🤘🏻🙌🏻☠️ ",
    "AUKAAT ME REH VRNA GAAND ME DANDA DAAL KE MUH SE NIKAAL DUNGA SHARIR BHI DANDE JESA DIKHEGA 🙄🤭🤭",
    "TERI MUMMY KE SAATH LUDO KHELTE KHELTE USKE MUH ME APNA LODA DE DUNGA☝🏻☝🏻😬",
    "TERI VAHEEN KO APNE LUND PR ITNA JHULAAUNGA KI JHULTE JHULTE HI BACHA PAIDA KR DEGI👀👯 ",
    "TERI MAA KI CHUT MEI BATTERY LAGA KE POWERBANK BANA DUNGA 🔋 🔥🤩",
    "TERI MAA KI CHUT MEI C++ STRING ENCRYPTION LAGA DUNGA BAHTI HUYI CHUT RUK JAYEGIIII😈🔥😍",
    "TERI MAA KE GAAND MEI JHAADU DAL KE MOR 🦚 BANA DUNGAA 🤩🥵😱",
    "TERI CHUT KI CHUT MEI SHOULDERING KAR DUNGAA HILATE HUYE BHI DARD HOGAAA😱🤮👺",
    "TERI MAA KO REDI PE BAITHAL KE USSE USKI CHUT BILWAUNGAA 💰 😵🤩",
    "BHOSDIKE TERI MAA KI CHUT MEI 4 HOLE HAI UNME MSEAL LAGA BAHUT BAHETI HAI BHOFDIKE👊🤮🤢🤢",
    "TERI BAHEN KI CHUT MEI BARGAD KA PED UGA DUNGAA CORONA MEI SAB OXYGEN LEKAR JAYENGE🤢🤩🥳",
    "TERI MAA KI CHUT MEI SUDO LAGA KE BIGSPAM LAGA KE 9999 FUCK LAGAA DU 🤩🥳🔥",
    "TERI VAHEN KE BHOSDIKE MEI BESAN KE LADDU BHAR DUNGA🤩🥳🔥😈",
    "TERI MAA KI CHUT KHOD KE USME CYLINDER ⛽️ FIT KARKE USMEE DAL MAKHANI BANAUNGAAA🤩👊🔥",
    "TERI MAA KI CHUT MEI SHEESHA DAL DUNGAAA AUR CHAURAHE PE TAANG DUNGA BHOSDIKE😈😱🤩",
    "TERI MAA KI CHUT MEI CREDIT CARD DAL KE AGE SE 500 KE KAARE KAARE NOTE NIKALUNGAA BHOSDIKE💰💰🤩",
    "TERI MAA KE SATH SUAR KA SEX KARWA DUNGAA EK SATH 6-6 BACHE DEGI💰🔥😱",
    "TERI BAHEN KI CHUT MEI APPLE KA 18W WALA CHARGER 🔥🤩",
    "TERI BAHEN KI GAAND MEI ONEPLUS KA WRAP CHARGER 30W HIGH POWER 💥😂😎",
    "TERI BAHEN KI CHUT KO AMAZON SE ORDER KARUNGA 10 rs MEI AUR FLIPKART PE 20 RS MEI BECH DUNGA🤮👿😈🤖",
    "TERI MAA KI BADI BHUND ME ZOMATO DAL KE SUBWAY KA BFF VEG SUB COMBO [15cm , 16 inches ] ORDER COD KRVAUNGA OR TERI MAA JAB DILIVERY DENE AYEGI TAB USPE JAADU KRUNGA OR FIR 9 MONTH BAAD VO EK OR FREE DILIVERY DEGI🙀👍🥳🔥",
    "TERI BHEN KI CHUT KAALI🙁🤣💥",
    "TERI MAA KI CHUT ME CHANGES COMMIT KRUGA FIR TERI BHEEN KI CHUT AUTOMATICALLY UPDATE HOJAAYEGI🤖🙏🤔",
    "TERI MAUSI KE BHOSDE MEI INDIAN RAILWAY 🚂💥😂",
    "TU TERI BAHEN TERA KHANDAN SAB BAHEN KE LAWDE RANDI HAI RANDI 🤢✅🔥",
    "TERI BAHEN KI CHUT MEI IONIC BOND BANA KE VIRGINITY LOOSE KARWA DUNGA USKI 📚 😎🤩",
    "TERI RANDI MAA SE PUCHNA BAAP KA NAAM BAHEN KE LODEEEEE 🤩🥳😳",
    "TU AUR TERI MAA DONO KI BHOSDE MEI METRO CHALWA DUNGA MADARXHOD 🚇🤩😱🥶",
    "TERI MAA KO ITNA CHODUNGA TERA BAAP BHI USKO PAHCHANANE SE MANA KAR DEGA😂👿🤩",
    "TERI BAHEN KE BHOSDE MEI HAIR DRYER CHALA DUNGAA💥🔥🔥",
    "TERI MAA KI CHUT MEI TELEGRAM KI SARI RANDIYON KA RANDI KHANA KHOL DUNGAA👿🤮😎",
    "TERI MAA KI CHUT ALEXA DAL KEE DJ BAJAUNGAAA 🎶 ⬆️🤩💥",
    "TERI MAA KE BHOSDE MEI GITHUB DAL KE APNA BOT HOST KARUNGAA 🤩👊👤😍",
    "TERI BAHEN KA VPS BANA KE 24*7 BASH CHUDAI COMMAND DE DUNGAA 🤩💥🔥🔥",
    "TERI MUMMY KI CHUT MEI TERE LAND KO DAL KE KAAT DUNGA MADARCHOD 🔪😂🔥",
    "SUN TERI MAA KA BHOSDA AUR TERI BAHEN KA BHI BHOSDA 👿😎👊",
    "TUJHE DEKH KE TERI RANDI BAHEN PE TARAS ATA HAI MUJHE BAHEN KE LODEEEE 👿💥🤩🔥",
    "SUN MADARCHOD JYADA NA UCHAL MAA CHOD DENGE EK MIN MEI ✅🤣🔥🤩",
    "APNI AMMA SE PUCHNA USKO US KAALI RAAT MEI KAUN CHODNEE AYA THAAA! TERE IS PAPA KA NAAM LEGI 😂👿😳",
    "TOHAR BAHIN CHODU BBAHEN KE LAWDE USME MITTI DAL KE CEMENT SE BHAR DU 🏠🤢🤩💥",
    "TUJHE AB TAK NAHI SMJH AYA KI MAI HI HU TUJHE PAIDA KARNE WALA BHOSDIKEE APNI MAA SE PUCH RANDI KE BACHEEEE 🤩👊👤😍",
    "TERI MAA KE BHOSDE MEI SPOTIFY DAL KE LOFI BAJAUNGA DIN BHAR 😍🎶🎶💥",
    "TERI MAA KA NAYA RANDI KHANA KHOLUNGA CHINTA MAT KAR 👊🤣🤣😳",
    "TERA BAAP HU BHOSDIKE TERI MAA KO RANDI KHANE PE CHUDWA KE US PAISE KI DAARU PEETA HU 🍷🤩🔥",
    "TERI BAHEN KI CHUT MEI APNA BADA SA LODA GHUSSA DUNGAA KALLAAP KE MAR JAYEGI 🤩😳😳🔥",
    "TOHAR MUMMY KI CHUT MEI PURI KI PURI KINGFISHER KI BOTTLE DAL KE TOD DUNGA ANDER HI 😱😂🤩",
    "TERI MAA KO ITNA CHODUNGA KI SAPNE MEI BHI MERI CHUDAI YAAD KAREGI RANDI 🥳😍👊💥",
    "TERI MUMMY AUR BAHEN KO DAUDA DAUDA NE CHODUNGA UNKE NO BOLNE PE BHI LAND GHUSA DUNGA ANDER TAK 😎😎🤣🔥",
    "TERI MUMMY KI CHUT KO ONLINE OLX PE BECHUNGA AUR PAISE SE TERI BAHEN KA KOTHA KHOL DUNGA 😎🤩😝😍",
    "TERI MAA KE BHOSDA ITNA CHODUNGA KI TU CAH KE BHI WO MAST CHUDAI SE DUR NHI JA PAYEGAA 😏😏🤩😍",
    "SUN BE RANDI KI AULAAD TU APNI BAHEN SE SEEKH KUCH KAISE GAAND MARWATE HAI😏🤬🔥💥",
    "TERI MAA KA YAAR HU MEI AUR TERI BAHEN KA PYAAR HU MEI AJA MERA LAND CHOOS LE 🤩🤣💥",
    "TERI BHEN KI CHUT ME USERBOT LAGAAUNGA SASTE SPAM KE CHODE",
    "TERI MAA KI GAAND ME SARIYA DAAL DUNGA MADARCHOD USI SARIYE PR TANG KE BACHE PAIDA HONGE 😱😱",
    "TERI MAA KI CHUT ME ✋ HATTH DALKE 👶 BACCHE NIKAL DUNGA 😍",
    "TERI BEHN KI CHUT ME KELE KE CHILKE 🤤🤤",
    "TERI MAA KI CHUT ME SUTLI BOMB FOD DUNGA TERI MAA KI JHAATE JAL KE KHAAK HO JAYEGI💣💋",
    "TERI VAHEEN KO HORLICKS PEELAKE CHODUNGA MADARCHOD😚",
    "TERI ITEM KI GAAND ME LUND DAALKE,TERE JAISA EK OR NIKAAL DUNGA MADARCHOD😆🤤💋",
    "TERI VAHEEN KO APNE LUND PR ITNA JHULAAUNGA KI JHULTE JHULTE HI BACHA PAIDA KR DEGI 💦💋",
    "SUAR KE PILLE TERI MAAKO SADAK PR LITAKE CHOD DUNGA 😂😆🤤",
    "ABE TERI MAAKA BHOSDA MADERCHOOD KR PILLE PAPA SE LADEGA TU 😼😂🤤",
    "GALI GALI NE SHOR HE TERI MAA RANDI CHOR HE 💋💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE PILLE KUTTE KE CHODE 😂👻🔥",
    "TERI MAAKO AISE CHODA AISE CHODA TERI MAAA BED PEHI MUTH DIA 💦💦💦💦",
    "TERI BEHEN KE BHOSDE ME AAAG LAGADIA MERA MOTA LUND DALKE 🔥🔥💦😆😆",
    "RANDIKE BACHHE TERI MAAKO CHODU CHAL NIKAL",
    "KITNA CHODU TERI RANDI MAAKI CHUTH ABB APNI BEHEN KO BHEJ 😆👻🤤",
    "TERI BEHEN KOTO CHOD CHODKE PURA FAAD DIA CHUTH ABB TERI GF KO BHEJ 😆💦🤤",
    "TERI GF KO ETNA CHODA BEHEN KE LODE TERI GF TO MERI RANDI BANGAYI ABB CHAL TERI MAAKO CHODTA FIRSE ♥️💦😆😆😆😆",
    "HARI HARI GHAAS ME JHOPDA TERI MAAKA BHOSDA 🤣🤣💋💦",
    "CHAL TERE BAAP KO BHEJ TERA BASKA NHI HE PAPA SE LADEGA TU",
    "TERI BEHEN KI CHUTH ME BOMB DALKE UDA DUNGA MAAKE LAWDE",
    "TERI MAAKO TRAIN ME LEJAKE TOP BED PE LITAKE CHOD DUNGA SUAR KE PILLE 🤣🤣💋💋",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI BEHEN KO CHOD CHODKE VIDEO BANAKE XNXX.COM PE NEELAM KARDUNGA KUTTE KE PILLE 💦💋",
    "TERI MAAAKI CHUDAI KO PORNHUB.COM PE UPLOAD KARDUNGA SUAR KE CHODE 🤣💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE BACHHE TEREKO CHAKKO SE PILWAVUNGA RANDIKE BACHHE 🤣🤣",
    "TERI MAAKI CHUTH FAADKE RAKDIA MAAKE LODE JAA ABB SILWALE 👄👄",
    "TERI BEHEN KI CHUTH ME MERA LUND KAALA",
    "TERI BEHEN LETI MERI LUND BADE MASTI SE TERI BEHEN KO MENE CHOD DALA BOHOT SASTE SE",
    "BETE TU BAAP SE LEGA PANGA TERI MAAA KO CHOD DUNGA KARKE NANGA 💦💋",
    "HAHAHAH MERE BETE AGLI BAAR APNI MAAKO LEKE AAYA MATH KAT OR MERE MOTE LUND SE CHUDWAYA MATH KAR",
    "CHAL BETA TUJHE MAAF KIA 🤣 ABB APNI GF KO BHEJ",
    "SHARAM KAR TERI BEHEN KA BHOSDA KITNA GAALIA SUNWAYEGA APNI MAAA BEHEN KE UPER",
    "ABE RANDIKE BACHHE AUKAT NHI HETO APNI RANDI MAAKO LEKE AAYA MATH KAR HAHAHAHA",
    "KIDZ MADARCHOD TERI MAAKO CHOD CHODKE TERR LIYE BHAI DEDIYA",
    "JUNGLE ME NACHTA HE MORE TERI MAAKI CHUDAI DEKKE SAB BOLTE ONCE MORE ONCE MORE 🤣🤣💦💋",
    "GALI GALI ME REHTA HE SAND TERI MAAKO CHOD DALA OR BANA DIA RAND 🤤🤣",
    "SAB BOLTE MUJHKO PAPA KYOUNKI MENE BANADIA TERI MAAKO PREGNENT 🤣🤣",
    "SUAR KE PILLE TERI MAAKI CHUTH ME SUAR KA LOUDA OR TERI BEHEN KI CHUTH ME MERA LODA",
    "CHAL CHAL APNI MAAKI CHUCHIYA DIKA",
    "HAHAHAHA BACHHE TERI MAAAKO CHOD DIA NANGA KARKE",
    "TERI GF HE BADI SEXY USKO PILAKE CHOODENGE PEPSI",
    "2 RUPAY KI PEPSI TERI MUMMY SABSE SEXY 💋💦",
    "TERI MAAKO CHEEMS SE CHUDWAVUNGA MADERCHOOD KE PILLE 💦🤣",
    "TERI BEHEN KI CHUTH ME MUTHKE FARAR HOJAVUNGA HUI HUI HUI",
    "SPEED LAAA TERI BEHEN CHODU RANDIKE PILLE 💋💦🤣",
    "ARE RE MERE BETE KYOUN SPEED PAKAD NA PAAA RAHA APNE BAAP KA HAHAH🤣🤣",
    "SUN SUN SUAR KE PILLE JHANTO KE SOUDAGAR APNI MUMMY KI NUDES BHEJ",
    "ABE SUN LODE TERI BEHEN KA BHOSDA FAAD DUNGA",
    "TERI MAAKO KHULE BAJAR ME CHOD DALA 🤣🤣💋",
]


MRAID = [
    "Tere naalo challiye haseen koyi NA 😁😁",
    "Taare chann ambar zameen koyi nA",
    "Main Jado Tere Mode Utte Sir Rakheya🧐🧐",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😖😖",
    "Sohniyan Vi Laggan Giyan Fer Walian😍😍",
    "Galan Nal Jado Takraiyan Waliyan🥰🥰",
    "Tare Dekhi Labh Labh Kiven Harde😁😁",
    "Tu Bala Ch Lakoiyan Jado Ratan Kaliyan😒😒",
    "Main Sab Kuj Har Tere Utton De’unga😌😌",
    "Sab Kuj War Tere Utton De’unga😉😉",
    "Akhir Ch Jan Tainu De’un Apni😎😎",
    "Chala Tainu Bhavein Pehli War De’unga😚😚",
    "Han Main Cheti Cheti Lawan😫😫",
    "Tere Nal Laini an😣😣",
    "Samay Da Tan Bhora Vi Yakeen Koi Na🥺🥺",
    "Tere Nalo Jhaliye Haseen Koi Na🥰🥰",
    "Tare Chann Ambar Zameen Koi Na😘😘",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Main Jado Tere Mode Utte Sir Rakheya😁😁",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😒😒",
    "Tu Yar Mera Tu Hi Ae Sahara AdiyE",
    "Main Pani Tera Mera Tu Kinara Adiye",
    "Phul Ban Jai Main Khushboo Bann Ju",
    "Deevan Bani Mera Teri Lau Ban Ju",
    "Haye Ujadiyan Thawan Te Banate Bag Ne",
    "Teriyan Ankhan Ne Kitte Jadu Yad Ne",
    "Jado Wang Kolon Phadi Vi Ni KassKe",
    "Totte Sambh Rakhe Tutte Hoye Kach De",
    "Han Ki Dil Yadan Rakhda Ae, Sambh Sambh Ke",
    "Hor Dil Sajjna Machine Koi Na",
    "Tere Nalo Jhaliye Haseen Koi Na",
    "Tare Chann Ambar Zameen Koi Na",
    "Tere Nalo Jhaliye Haseen Koi Na",
    "Tare Chann Ambar Zameen Koi Na",
    "Main Jado Tere Mode Utte Sir Rakheya",
    "Eh Ton Sachi Sama Vi Haseen Koi Na",
    "Kine Din Hogye Meri Akh Soi Na",
    "Tere Ton Bagair Mera Aithe Koi Na",
    "Tu Bhukh Vi Ae Tu Hi Ae Guzara Adiye",
    "Mannu Sab Kari Tu Ishara Adiye",
    "Ho Khaure Kinni War Seene Vich Khubiyan",
    "Surme De Vich Dovein Ankhan Dubbiyan",
    "Kini Sohni Lagge Jadon Chup Kar Je",
    "Jandi Jandi Shaman Nu Vi Dhup Kar Je",
    "Haye Main Paun Farmaishi Rang Tere Sohniye",
    "Unj Bahotan Gifty Shaukeen Koi Na",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Main Jado Tere Mode Utte Sir Rakheya😁😁",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😒😒",
    "Kanna Wich Jhumka👀👀",
    "Akhan Wich Surma🙈🙈",
    "Ho Jaise Strawberry Candy😋😋",
    "Nakk Utte Koka🤨🤨",
    "Jeena Kare Aukha🤭🤭",
    "Haye Meri Jaan Kadd Laindi😌😌",
    "Tere Nakhre Haye Tauba Sanu Maarde🤫🤫",
    "Ho Gaya Hai Mera Baby Bura HaaL😊😊",
    "Sachi Lut Gaye Hum Tere Is Pyar Mein😏😏",
    "Jeeni Zindagi Hai Bas Tere Naal😚😚",
    "cause I Love You 😘😘",
    "I Love YoU SO MUCH 😍😍",
    "cause I Love You 😘😘",
    "I Love YoU SO MUCH 😍😍",
    "Sapno Mein Mere AayI😝😝",
    "Uff Oh Phir Neendein Hi Churayi😜😜",
    "Oh No! Tera Husan Nazara🥰🥰",
    "Baby! Lage Sohna Kitna PyarA😚😚",
    "Sapno Mein Mere Aayi😝😝",
    "Uff Oh Phir Neendein Hi Churayi😜😜",
    "Oh No! Tera Husan Nazara🥰🥰",
    "Baby! Lage Sohna Kitna PyarA😚😚",
    "Tainu Diamond Mundri Pehnawa😎😎",
    "Naale Duniya Sari Ghumawa🙈🙈",
    "Chhoti-Chhoti Gallan Utte Main Hasavaan💙💙",
    "Yaara Kade Vi Na Tainu Main Rulawaan🙊🙊",
    "cause I Love You  🙈🙈",
    "I Love You ❤️❤️",
    "cause I Love You🙈🙈",
    "I Love You ❤️❤️",
    "Yaari Laawan Sachi YaarI💫💫",
    "Tu Jaan Ton Vi Pyari😁😁",
    "Will Love You To The Moon And Back😆😆",
    "Hogi Saza Na Koyi Hogi😙😙",
    "Chahe Karun Chori Chaand Taare😉😉",
    "Imma Give You Them😅😅",
    "Yaari Laavan Sachi YaarI😘😘",
    "Tu Jaan Ton Vi PyarI😆😆",
    "Will Love You To The Moon And Back💕💕",
    "Hogee Sazaa Na Koyi Hogi💓💓",
    "Chahe Karun Chori Chaand Taare🥺🥺",
    "Imma Give You Them🥵🥵",
    "Puri Karunga Main Teri Sari Khahishein😁😁",
    "Tera Rakhanga Main Rajj Ke Khayal😘😘",
    "Kitni Khoobiyan Hai Tere Is Yaar Mein🥰🥰",
    "Aaja Bahon Mein Tu Bahein Bas Daal😂😂",
    "Aur Hota Nahi Ab Intezar🤩🤩",
    "Aur Hota Nahee Ab Intezaar😘😘",
    "cause I Love You 😍😍",
    "I Love YoU 😙😙",
    "cause I Love You",
    "I Love YoU SOOOOOOOOOOOOOOOOOO MUCHHHHHHHHHHHHHHHHHHHHH 😘😘",
    "WILL U BE MINE FOREVER??🤔🤔",
    "Je tu akh te main aan kaajal ve😌😌",
    "Tu baarish te main baadal ve🤫🤫",
    "Tu deewana main aan paagal ve🤪🤪",
    "Sohneya sohneya☺️☺️",
    "Je tu chann te main aan taara ve🤗🤗",
    "Main lehar te tu kinara ve😶😶",
    "Main aadha te tu saara ve🤗🤗",
    "Sohneya sohneya😗😗",
    "Tu jahan hai main wahan😘😘",
    "Tere bin main hoon hi kya🥲🥲",
    "Tere bin chehre se mere🤔🤔",
    "Udd jaaye rang ve😅😅",
    "Tujhko paane ke liye huM😁😁",
    "Roz mangein mannat ve🙈🙈",
    "Duniya to kya cheez hai yaara🙉🙉",
    "Thukra denge jannat ve😌😌",
    "Tujhko paane ke liye hum😌😌",
    "Roz mangein mannat ve🤫🤫",
    "Duniya to kya cheez hai yaara🤔🤔",
    "Thukra denge jannat ve😌😌",
    "Na parwah mainu apni aa😁😁",
    "Na parwah mainu duniya di👅👅",
    "Na parwah mainu apni aa😅😅",
    "Na parwah mainu duniya di👅👅",
    "Tere ton juda nahi kar sakdi🤬🤬",
    "Koyi taakat mainu duniya di😈😈",
    "Dooron aa jaave teri khushbu😎😎",
    "Akhan hun band taan vi vekh lawan😍😍",
    "Teri gali vich mera auna har roz😋😋",
    "Tera ghar jadon aave matha tek lawan😌😌",
    "Nirmaan tujhko dekh ke😏😏",
    "Aa jaave himmat ve😉😉",
    "Tujhko paane ke liye hum😊😊",
    "Roz mangein mannat ve😉😉",
    "Duniya to kya cheez hai yaara😌😌",
    "Thukra denge jannat ve😍😍",
    "Tujhko paane ke liye hum🤫🤫",
    "Roz mangein mannat ve😁😁",
    "Duniya to kya cheez hai yaara😏😏",
    "Thukra denge jannat ve😌😌",
    "SO MISS 😶😶",
    "KYA SOCHA APNE BAARE MAIN😆😆",
    "BADI MUSHKIL SE YEH SAB KARA H RE🥵🥵",
    "PAHLE PURA BOT HI KANG MAAR DIYA BUT🤫🤫",
    "WAHI ERROR AAYE JO AATE THE🥲🥲",
    "BUT TUMHARA HO CHUKA WALA BF😎😎",
    "AND FUTURE HUSBAND JO BANNE WALA THA WO BHOT SMART H RE😌😌",
    "ISS BAAR BOT BANAYA AND CHOTA SA EDIT KARA BAS😁😁",
    "AUR DEKO ABHI TUM USSI BOT SE YEH PADH PAA RHI😂😂",
    "HEHE BTW YEH CHORO MEKO NA TUMSE😶😶",
    "KUCH PUCHNA THA KI ME🤔🤔",
    "TUMHARE KABIL HU YA",
    "TUMHARE KABIL NHI😂💓",
    "AND EK AUR BAAT BOLNI THI KI😙😙",
    "I REALLY REALLY DEEPLY😙😙",
    "LOVE YOU FROM MY HEART TO YOUR HEAT AND MY SOUL ATTACHED BY YOUR SOUL CAN YOU BE MINE FOREVER😌😌❤️"
]
FLASHSPAM = [5178643838, 5151463162, 1877225844, 5031289767]

MRAID = [
    "Tere naalo challiye haseen koyi NA 😁😁",
    "Taare chann ambar zameen koyi nA",
    "Main Jado Tere Mode Utte Sir Rakheya🧐🧐",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😖😖",
    "Sohniyan Vi Laggan Giyan Fer Walian😍😍",
    "Galan Nal Jado Takraiyan Waliyan🥰🥰",
    "Tare Dekhi Labh Labh Kiven Harde😁😁",
    "Tu Bala Ch Lakoiyan Jado Ratan Kaliyan😒😒",
    "Main Sab Kuj Har Tere Utton De’unga😌😌",
    "Sab Kuj War Tere Utton De’unga😉😉",
    "Akhir Ch Jan Tainu De’un Apni😎😎",
    "Chala Tainu Bhavein Pehli War De’unga😚😚",
    "Han Main Cheti Cheti Lawan😫😫",
    "Tere Nal Laini an😣😣",
    "Samay Da Tan Bhora Vi Yakeen Koi Na🥺🥺",
    "Tere Nalo Jhaliye Haseen Koi Na🥰🥰",
    "Tare Chann Ambar Zameen Koi Na😘😘",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Main Jado Tere Mode Utte Sir Rakheya😁😁",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😒😒",
    "Kanna Wich Jhumka👀👀",
    "Akhan Wich Surma🙈🙈",
    "Ho Jaise Strawberry Candy😋😋",
    "Nakk Utte Koka🤨🤨",
    "Jeena Kare Aukha🤭🤭",
    "Haye Meri Jaan Kadd Laindi😌😌",
    "Tere Nakhre Haye Tauba Sanu Maarde🤫🤫",
    "Ho Gaya Hai Mera Baby Bura HaaL😊😊",
    "Sachi Lut Gaye Hum Tere Is Pyar Mein😏😏",
    "Jeeni Zindagi Hai Bas Tere Naal😚😚",
    "cause I Love You NYRA😘😘",
    "I Love YoU SO MUCH NYRA😍😍",
    "cause I Love You NYRA😘😘",
    "I Love YoU SO MUCH NYRA😍😍",
    "Sapno Mein Mere AayI😝😝",
    "Uff Oh Phir Neendein Hi Churayi😜😜",
    "Oh No! Tera Husan Nazara🥰🥰",
    "Baby! Lage Sohna Kitna PyarA😚😚",
    "Sapno Mein Mere Aayi😝😝",
    "Uff Oh Phir Neendein Hi Churayi😜😜",
    "Oh No! Tera Husan Nazara🥰🥰",
    "Baby! Lage Sohna Kitna PyarA😚😚",
    "Tainu Diamond Mundri Pehnawa😎😎",
    "Naale Duniya Sari Ghumawa🙈🙈",
    "Chhoti-Chhoti Gallan Utte Main Hasavaan💙💙",
    "Yaara Kade Vi Na Tainu Main Rulawaan🙊🙊",
    "cause I Love You🙈🙈",
    "I Love You NYRA❤️❤️",
    "cause I Love You🙈🙈",
    "I Love You NYRA❤️❤️",
    "Yaari Laawan Sachi YaarI💫💫",
    "Tu Jaan Ton Vi Pyari😁😁",
    "Will Love You To The Moon And Back😆😆",
    "Hogi Saza Na Koyi Hogi😙😙",
    "Chahe Karun Chori Chaand Taare😉😉",
    "Imma Give You Them😅😅",
    "Yaari Laavan Sachi YaarI😘😘",
    "Tu Jaan Ton Vi PyarI😆😆",
    "Will Love You To The Moon And Back💕💕",
    "Hogee Sazaa Na Koyi Hogi💓💓",
    "Chahe Karun Chori Chaand Taare🥺🥺",
    "Imma Give You Them🥵🥵",
    "Puri Karunga Main Teri Sari Khahishein😁😁",
    "Tera Rakhanga Main Rajj Ke Khayal😘😘",
    "Kitni Khoobiyan Hai Tere Is Yaar Mein🥰🥰",
    "Aaja Bahon Mein Tu Bahein Bas Daal😂😂",
    "Aur Hota Nahi Ab Intezar🤩🤩",
    "Aur Hota Nahee Ab Intezaar😘😘",
    "cause I Love You NYRA😍😍",
    "I Love YoU NYRA😙😙",
    "cause I Love You NYRA",
    "I Love YoU SOOOOOOOOOOOOOOOOOO MUCHHHHHHHHHHHHHHHHHHHHH NYRAAAAAAAAAAAAAAAAAAAAA😘😘",
    "WILL U BE MINE FOREVER??🤔🤔",
    "Je tu akh te main aan kaajal ve😌😌",
    "Tu baarish te main baadal ve🤫🤫",
    "Tu deewana main aan paagal ve🤪🤪",
    "Sohneya sohneya☺️☺️",
    "Je tu chann te main aan taara ve🤗🤗",
    "Main lehar te tu kinara ve😶😶",
    "Main aadha te tu saara ve🤗🤗",
    "Sohneya sohneya😗😗",
    "Tu jahan hai main wahan😘😘",
    "Tere bin main hoon hi kya🥲🥲",
    "Tere bin chehre se mere🤔🤔",
    "Udd jaaye rang ve😅😅",
    "Tujhko paane ke liye huM😁😁",
    "Roz mangein mannat ve🙈🙈",
    "Duniya to kya cheez hai yaara🙉🙉",
    "Thukra denge jannat ve😌😌",
    "Tujhko paane ke liye hum😌😌",
    "Roz mangein mannat ve🤫🤫",
    "Duniya to kya cheez hai yaara🤔🤔",
    "Thukra denge jannat ve😌😌",
    "Na parwah mainu apni aa😁😁",
    "Na parwah mainu duniya di👅👅",
    "Na parwah mainu apni aa😅😅",
    "Na parwah mainu duniya di👅👅",
    "Tere ton juda nahi kar sakdi🤬🤬",
    "Koyi taakat mainu duniya di😈😈",
    "Dooron aa jaave teri khushbu😎😎",
    "Akhan hun band taan vi vekh lawan😍😍",
    "Teri gali vich mera auna har roz😋😋",
    "Tera ghar jadon aave matha tek lawan😌😌",
    "Nirmaan tujhko dekh ke😏😏",
    "Aa jaave himmat ve😉😉",
    "Tujhko paane ke liye hum😊😊",
    "Roz mangein mannat ve😉😉",
    "Duniya to kya cheez hai yaara😌😌",
    "Thukra denge jannat ve😍😍",
    "Tujhko paane ke liye hum🤫🤫",
    "Roz mangein mannat ve😁😁",
    "Duniya to kya cheez hai yaara😏😏",
    "Thukra denge jannat ve😌😌",
    "SO MISS AADHYA UFF NYRA😶😶",
    "KYA SOCHA APNE BAARE MAIN😆😆",
    "BADI MUSHKIL SE YEH SAB KARA H RE🥵🥵",
    "PAHLE PURA BOT HI KANG MAAR DIYA BUT🤫🤫",
    "WAHI ERROR AAYE JO AATE THE🥲🥲",
    "BUT TUMHARA HONE WALA BF😎😎",
    "AND FUTURE HUSBAND BHOT SMART H RE😌😌",
    "ISS BAAR BOT BANAYA AND CHOTA SA EDIT KARA BAS😁😁",
    "AUR DEKO ABHI TUM USSI BOT SE YEH PADH PAA RHI😂😂",
    "HEHE BTW YEH CHORO MEKO NA TUMSE😶😶",
    "KUCH PUCHNA THA KI ME🤔🤔",
    "TUMHARE KABIL HU YA",
    "TUMHARE KABIL NHI😂💓",
    "AND EK AUR BAAT BOLNI THI KI😙😙",
    "I REALLY REALLY DEEPLY😙😙",
    "LOVE YOU FROM MY HEART TO YOUR HEAT AND MY SOUL ATTACHED BY YOUR SOUL CAN YOU BE MINE FOREVER😌😌❤️",
]

GROUP = [-1001505103664, -1001615383952, -1001480070153]


RRAID = [
    "MADARCHOD",
    "BHOSDIKE",
    "LAAAWEEE KE BAAAAAL",
    "MAAAAR KI JHAAAAT KE BBBBBAAAAALLLLL",
    "MADRCHOD..",
    "TERI MA KI CHUT..",
    "LWDE KE BAAALLL.",
    "MACHAR KI JHAAT KE BAAALLLL",
    "TERI MA KI CHUT M DU TAPA TAP?",
    "TERI MA KA BHOSDAA",
    "TERI BHN SBSBE BDI RANDI.",
    "TERI MA OSSE BADI RANDDDDD",
    "TERA BAAP CHKAAAA",
    "KITNI CHODU TERI MA AB OR..",
    "TERI MA CHOD DI HM NE",
    "TERI MA KE STH REELS BNEGA ROAD PEE",
    "TERI MA KI CHUT EK DAM TOP SEXY",
    "MALUM NA PHR KESE LETA HU M TERI MA KI CHUT TAPA TAPPPPP",
    "LUND KE CHODE TU KEREGA TYPIN",
    "SPEED PKD LWDEEEE",
    "BAAP KI SPEED MTCH KRRR",
    "LWDEEE",
    "PAPA KI SPEED MTCH NHI HO RHI KYA",
    "ALE ALE MELA BCHAAAA",
    "CHUD GYA PAPA SEEE",
    "KISAN KO KHODNA OR",
    "SALE RAPEKL KRDKA TERA",
    "HAHAHAAAAA",
    "KIDSSSS",
    "TERI MA CHUD GYI AB FRAR MT HONA",
    "YE LDNGE BAPP SE",
    "KIDSSS FRAR HAHAHH",
    "BHEN KE LWDE SHRM KR",
    "KITNI GLIYA PDWEGA APNI MA KO",
    "NALLEE",
    "SUAR KE PILLE TERI MAAKO SADAK PR LITAKE CHOD DUNGA 😂😆🤤",
    "ABE TERI MAAKA BHOSDA MADERCHOOD KR PILLE PAPA SE LADEGA TU 😼😂🤤",
    "GALI GALI NE SHOR HE TERI MAA RANDI CHOR HE 💋💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE PILLE KUTTE KE CHODE 😂👻🔥",
    "TERI MAAKO AISE CHODA AISE CHODA TERI MAAA BED PEHI MUTH DIA 💦💦💦💦",
    "TERI BEHEN KE BHOSDE ME AAAG LAGADIA MERA MOTA LUND DALKE 🔥🔥💦😆😆",
    "RANDIKE BACHHE TERI MAAKO CHODU CHAL NIKAL",
    "KITNA CHODU TERI RANDI MAAKI CHUTH ABB APNI BEHEN KO BHEJ 😆👻🤤",
    "TERI BEHEN KOTO CHOD CHODKE PURA FAAD DIA CHUTH ABB TERI GF KO BHEJ 😆💦🤤",
    "TERI GF KO ETNA CHODA BEHEN KE LODE TERI GF TO MERI RANDI BANGAYI ABB CHAL TERI MAAKO CHODTA FIRSE ♥️💦😆😆😆😆",
    "HARI HARI GHAAS ME JHOPDA TERI MAAKA BHOSDA 🤣🤣💋💦",
    "CHAL TERE BAAP KO BHEJ TERA BASKA NHI HE PAPA SE LADEGA TU",
    "TERI BEHEN KI CHUTH ME BOMB DALKE UDA DUNGA MAAKE LAWDE",
    "TERI MAAKO TRAIN ME LEJAKE TOP BED PE LITAKE CHOD DUNGA SUAR KE PILLE 🤣🤣💋💋",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI BEHEN KO CHOD CHODKE VIDEO BANAKE XNXX.COM PE NEELAM KARDUNGA KUTTE KE PILLE 💦💋",
    "TERI MAAAKI CHUDAI KO PORNHUB.COM PE UPLOAD KARDUNGA SUAR KE CHODE 🤣💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE BACHHE TEREKO CHAKKO SE PILWAVUNGA RANDIKE BACHHE 🤣🤣",
    "TERI MAAKI CHUTH FAADKE RAKDIA MAAKE LODE JAA ABB SILWALE 👄👄",
    "TERI BEHEN KI CHUTH ME MERA LUND KAALA",
    "TERI BEHEN LETI MERI LUND BADE MASTI SE TERI BEHEN KO MENE CHOD DALA BOHOT SASTE SE",
    "BETE TU BAAP SE LEGA PANGA TERI MAAA KO CHOD DUNGA KARKE NANGA 💦💋",
    "HAHAHAH MERE BETE AGLI BAAR APNI MAAKO LEKE AAYA MATH KAT OR MERE MOTE LUND SE CHUDWAYA MATH KAR",
    "CHAL BETA TUJHE MAAF KIA 🤣 ABB APNI GF KO BHEJ",
    "SHARAM KAR TERI BEHEN KA BHOSDA KITNA GAALIA SUNWAYEGA APNI MAAA BEHEN KE UPER",
    "ABE RANDIKE BACHHE AUKAT NHI HETO APNI RANDI MAAKO LEKE AAYA MATH KAR HAHAHAHA",
    "KIDZ MADARCHOD TERI MAAKO CHOD CHODKE TERR LIYE BHAI DEDIYA",
    "JUNGLE ME NACHTA HE MORE TERI MAAKI CHUDAI DEKKE SAB BOLTE ONCE MORE ONCE MORE 🤣🤣💦💋",
    "GALI GALI ME REHTA HE SAND TERI MAAKO CHOD DALA OR BANA DIA RAND 🤤🤣",
    "SAB BOLTE MUJHKO PAPA KYOUNKI MENE BANADIA TERI MAAKO PREGNENT 🤣🤣",
    "SUAR KE PILLE TERI MAAKI CHUTH ME SUAR KA LOUDA OR TERI BEHEN KI CHUTH ME MERA LODA",
    "CHAL CHAL APNI MAAKI CHUCHIYA DIKA",
    "HAHAHAHA BACHHE TERI MAAAKO CHOD DIA NANGA KARKE",
    "TERI GF HE BADI SEXY USKO PILAKE CHOODENGE PEPSI",
    "2 RUPAY KI PEPSI TERI MUMMY SABSE SEXY 💋💦",
    "TERI MAAKO CHEEMS SE CHUDWAVUNGA MADERCHOOD KE PILLE 💦🤣",
    "TERI BEHEN KI CHUTH ME MUTHKE FARAR HOJAVUNGA HUI HUI HUI",
    "SPEED LAAA TERI BEHEN CHODU RANDIKE PILLE 💋💦🤣",
    "ARE RE MERE BETE KYOUN SPEED PAKAD NA PAAA RAHA APNE BAAP KA HAHAH🤣🤣",
    "SUN SUN SUAR KE PILLE JHANTO KE SOUDAGAR APNI MUMMY KI NUDES BHEJ",
    "ABE SUN LODE TERI BEHEN KA BHOSDA FAAD DUNGA",
    "TERI MAAKO KHULE BAJAR ME CHOD DALA 🤣🤣💋",
    "SHRM KR",
    "MERE LUND KE BAAAAALLLLL",
    "KITNI GLIYA PDWYGA APNI MA BHEN KO",
    "RNDI KE LDKEEEEEEEEE",
    "KIDSSSSSSSSSSSS",
    "Apni gaand mein muthi daal",
    "Apni lund choos",
    "Apni ma ko ja choos",
    "Bhen ke laude",
    "Bhen ke takke",
    "Abla TERA KHAN DAN CHODNE KI BARIII",
    "BETE TERI MA SBSE BDI RAND",
    "LUND KE BAAAL JHAT KE PISSSUUUUUUU",
    "LUND PE LTKIT MAAALLLL KI BOND H TUUU",
    "KASH OS DIN MUTH MRKE SOJTA M TUN PAIDA NA HOTAA",
    "GLTI KRDI TUJW PAIDA KRKE",
    "SPEED PKDDD",
    "Gaand main LWDA DAL LE APNI MERAAA",
    "Gaand mein bambu DEDUNGAAAAAA",
    "GAND FTI KE BALKKK",
    "Gote kitne bhi bade ho, lund ke niche hi rehte hai",
    "Hazaar lund teri gaand main",
    "Jhaant ke pissu-",
    "TERI MA KI KALI CHUT",
    "Khotey ki aulda",
    "Kutte ka awlat",
    "Kutte ki jat",
    "Kutte ke tatte",
    "TETI MA KI.CHUT , tERI MA RNDIIIIIIIIIIIIIIIIIIII",
    "Lavde ke bal",
    "muh mei lele",
    "Lund Ke Pasine",
    "MERE LWDE KE BAAAAALLL",
    "HAHAHAAAAAA",
    "CHUD GYAAAAA",
    "Randi khanE KI ULADDD",
    "Sadi hui gaand",
    "Teri gaand main kute ka lund",
    "Teri maa ka bhosda",
    "Teri maa ki chut",
    "Tere gaand mein keede paday",
    "Ullu ke pathe",
    "SUNN MADERCHOD",
    "TERI MAA KA BHOSDA",
    "BEHEN K LUND",
    "TERI MAA KA CHUT KI CHTNIIII",
    "MERA LAWDA LELE TU AGAR CHAIYE TOH",
    "GAANDU",
    "CHUTIYA",
    "TERI MAA KI CHUT PE JCB CHADHAA DUNGA",
    "SAMJHAA LAWDE",
    "YA DU TERE GAAND ME TAPAA TAP��",
    "TERI BEHEN MERA ROZ LETI HAI",
    "TERI GF K SAATH MMS BANAA CHUKA HU���不�不",
    "TU CHUTIYA TERA KHANDAAN CHUTIYA",
    "AUR KITNA BOLU BEY MANN BHAR GAYA MERA�不",
    "TERIIIIII MAAAA KI CHUTTT ME ABCD LIKH DUNGA MAA KE LODE",
    "TERI MAA KO LEKAR MAI FARAR",
    "RANIDIII",
    "BACHEE",
    "CHODU",
    "RANDI",
    "RANDI KE PILLE",
    "TERIIIII MAAA KO BHEJJJ",
    "TERAA BAAAAP HU",
    "teri MAA KI CHUT ME HAAT DAALLKE BHAAG JAANUGA",
    "Teri maa KO SARAK PE LETAA DUNGA",
    "TERI MAA KO GB ROAD PE LEJAKE BECH DUNGA",
    "Teri maa KI CHUT MÉ KAALI MITCH",
    "TERI MAA SASTI RANDI HAI",
    "TERI MAA KI CHUT ME KABUTAR DAAL KE SOUP BANAUNGA MADARCHOD",
    "TERI MAAA RANDI HAI",
    "TERI MAAA KI CHUT ME DETOL DAAL DUNGA MADARCHOD",
    "TERI MAA KAAA BHOSDAA",
    "TERI MAA KI CHUT ME LAPTOP",
    "Teri maa RANDI HAI",
    "TERI MAA KO BISTAR PE LETAAKE CHODUNGA",
    "TERI MAA KO AMERICA GHUMAAUNGA MADARCHOD",
    "TERI MAA KI CHUT ME NAARIYAL PHOR DUNGA",
    "TERI MAA KE GAND ME DETOL DAAL DUNGA",
    "TERI MAAA KO HORLICKS PILAUNGA MADARCHOD",
    "TERI MAA KO SARAK PE LETAAA DUNGAAA",
    "TERI MAA KAA BHOSDA",
    "MERAAA LUND PAKAD LE MADARCHOD",
    "CHUP TERI MAA AKAA BHOSDAA",
    "TERIII MAA CHUF GEYII KYAAA LAWDEEE",
    "TERIII MAA KAA BJSODAAA",
    "MADARXHODDD",
    "TERIUUI MAAA KAA BHSODAAA",
    "TERIIIIII BEHENNNN KO CHODDDUUUU MADARXHODDDD",
    "NIKAL MADARCHOD",
    "RANDI KE BACHE",
    "TERA MAA MERI FAN",
    "TERI SEXY BAHEN KI CHUT OP",
]


PORMS = [
        "https://telegra.ph/file/9bcc076fd81dfe3feb291.mp4",
        "https://telegra.ph/file/b7a1a42429a65f64e67af.mp4",
        "https://telegra.ph/file/dc3da5a3eb77ae20fa21d.mp4",
        "https://telegra.ph/file/22b89774a4ba9219d530b.mp4",
        "https://telegra.ph/file/7b15fbca08ae1e73e559c.mp4",
        "https://telegra.ph/file/a9c1dea3f34925bb60686.mp4",
        "https://telegra.ph/file/913b4e567b7f435b7f0db.mp4",
        "https://telegra.ph/file/5a5d1a919a97af2314955.mp4",
        "https://telegra.ph/file/0f8b903669600d304cbe4.mp4",
        "https://telegra.ph/file/f3816b54c9eb7617356b6.mp4",
        "https://telegra.ph/file/516dbaa03fde1aaa70633.mp4",
        "https://telegra.ph/file/07bba6ead0f1e381b1bd1.mp4",
        "https://telegra.ph/file/0a4f7935df9b4ab8d62ed.mp4",
        "https://telegra.ph/file/40966bf68c0e4dbe18058.mp4",
        "https://telegra.ph/file/50637aa9c04d136687523.mp4",
        "https://telegra.ph/file/b81c0b0e491da73e64260.mp4",
        "https://telegra.ph/file/4ddf5f29783d92ae03804.mp4",
        "https://telegra.ph/file/4037dc2517b702cc208b1.mp4",
        "https://telegra.ph/file/33cebe2798c15d52a2547.mp4",
        "https://telegra.ph/file/4dc3c8b03616da516104a.mp4",
        "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
        "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
        "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
        "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
        "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
        "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
        "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
        "https://telegra.ph/file/0f23807ed1930704e2bef.jpg",
        "https://telegra.ph/file/c49280b8f1dcecaf86c00.jpg",
        "https://telegra.ph/file/f483400ff141de73767ca.jpg",
        "https://telegra.ph/file/1543bbea4e3c1abb6764a.jpg",
        "https://telegra.ph/file/a0d77be0d769c7cd334ab.jpg",
        "https://telegra.ph/file/6c6e93860527d2f577df8.jpg",
        "https://telegra.ph/file/d987b0e72eb3bb4801f01.jpg",
        "https://telegra.ph/file/b434999287d3580250960.jpg",
        "https://telegra.ph/file/0729cc082bf97347988f7.jpg",
        "https://telegra.ph/file/bb96d25df82178a2892e7.jpg",
        "https://telegra.ph/file/be73515791ea33be92a7d.jpg",
        "https://telegra.ph/file/fe234d6273093282d2dcc.jpg",
        "https://telegra.ph/file/66254bb72aa8094d38250.jpg",
        "https://telegra.ph/file/44bdaf37e5f7bdfc53ac6.jpg",
        "https://telegra.ph/file/e561ee1e1ca88db7e8038.jpg",
        "https://telegra.ph/file/f1960ccfc866b29ea5ad2.jpg",
        "https://telegra.ph/file/97622cad291472fb3c4aa.jpg",
        "https://telegra.ph/file/a46e316b413e9dc43e91b.jpg",
        "https://telegra.ph/file/497580fc3bddc21e0e162.jpg",
        "https://telegra.ph/file/3e86cc6cab06a6e2bde82.jpg",
        "https://telegra.ph/file/83140e2c57ddd95f310e6.jpg",
        "https://telegra.ph/file/2b20f8509d9437e94fed5.jpg",
        "https://telegra.ph/file/571960dcee4fce56698a4.jpg",
        "https://telegra.ph/file/25929a0b49452d8946c14.mp4",
        "https://telegra.ph/file/f5c9ceded3ee6e76a5931.jpg",
        "https://telegra.ph/file/a8bf6c6df8a48e4a306ca.jpg",
        "https://telegra.ph/file/af9e3f98da0bd937adf6e.jpg",
]
